// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/Wei-Shaw/sub2api/ent"
	"github.com/Wei-Shaw/sub2api/internal/config"
	"github.com/Wei-Shaw/sub2api/internal/orchestrator"
	"github.com/Wei-Shaw/sub2api/internal/repository"
	"github.com/Wei-Shaw/sub2api/internal/service"
	"github.com/redis/go-redis/v9"
	"log"
	"time"
)

import (
	_ "github.com/Wei-Shaw/sub2api/ent/runtime"
)

// Injectors from wire.go:

func initializeOrchestrator() (*orchestrator.Service, func(), error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	client, err := repository.ProvideEnt(configConfig)
	if err != nil {
		return nil, nil, err
	}
	db, err := repository.ProvideSQLDB(client)
	if err != nil {
		return nil, nil, err
	}
	apiKeyRepository := repository.NewAPIKeyRepository(client, db)
	userRepository := repository.NewUserRepository(client, db)
	groupRepository := repository.NewGroupRepository(client, db)
	userSubscriptionRepository := repository.NewUserSubscriptionRepository(client)
	userGroupRateRepository := repository.NewUserGroupRateRepository(db)
	redisClient := repository.ProvideRedis(configConfig)
	apiKeyCache := repository.NewAPIKeyCache(redisClient)
	billingCache := repository.NewBillingCache(redisClient)
	userRPMCache := repository.NewUserRPMCache(redisClient)
	billingCacheService := service.ProvideBillingCacheService(billingCache, userRepository, userSubscriptionRepository, apiKeyRepository, userRPMCache, userGroupRateRepository, configConfig)
	apiKeyService := service.ProvideAPIKeyService(apiKeyRepository, userRepository, groupRepository, userSubscriptionRepository, userGroupRateRepository, apiKeyCache, configConfig, billingCacheService)
	keyAuthenticator := provideKeyAuthenticator(apiKeyService)
	schedulerCache := repository.ProvideSchedulerCache(redisClient, configConfig)
	accountRepository := repository.NewAccountRepository(client, db, schedulerCache)
	usageLogRepository := repository.NewUsageLogRepository(client, db)
	usageBillingRepository := repository.NewUsageBillingRepository(client, db)
	gatewayCache := repository.NewGatewayCache(redisClient)
	schedulerOutboxRepository := repository.NewSchedulerOutboxRepository(db)
	schedulerSnapshotService := service.ProvideSchedulerSnapshotService(schedulerCache, schedulerOutboxRepository, accountRepository, groupRepository, configConfig)
	concurrencyCache := repository.ProvideConcurrencyCache(redisClient, configConfig)
	concurrencyService := service.ProvideConcurrencyService(concurrencyCache, accountRepository, configConfig)
	pricingRemoteClient := repository.ProvidePricingRemoteClient(configConfig)
	pricingService, err := service.ProvidePricingService(configConfig, pricingRemoteClient)
	if err != nil {
		return nil, nil, err
	}
	billingService := service.NewBillingService(configConfig, pricingService)
	settingRepository := repository.NewSettingRepository(client)
	geminiQuotaService := service.NewGeminiQuotaService(configConfig, settingRepository)
	tempUnschedCache := repository.NewTempUnschedCache(redisClient)
	timeoutCounterCache := repository.NewTimeoutCounterCache(redisClient)
	openAI403CounterCache := repository.NewOpenAI403CounterCache(redisClient)
	proxyRepository := repository.NewProxyRepository(client, db)
	settingService := service.ProvideSettingService(settingRepository, groupRepository, proxyRepository, configConfig)
	geminiTokenCache := repository.NewGeminiTokenCache(redisClient)
	compositeTokenCacheInvalidator := service.NewCompositeTokenCacheInvalidator(geminiTokenCache)
	rateLimitService := service.ProvideRateLimitService(accountRepository, usageLogRepository, configConfig, geminiQuotaService, tempUnschedCache, timeoutCounterCache, openAI403CounterCache, settingService, compositeTokenCacheInvalidator)
	httpUpstream := repository.NewHTTPUpstream(configConfig)
	timingWheelService, err := service.ProvideTimingWheelService()
	if err != nil {
		return nil, nil, err
	}
	deferredService := service.ProvideDeferredService(accountRepository, timingWheelService)
	openAIOAuthClient := repository.NewOpenAIOAuthClient()
	openAIOAuthService := service.NewOpenAIOAuthService(proxyRepository, openAIOAuthClient)
	oAuthRefreshAPI := service.ProvideOAuthRefreshAPI(accountRepository, geminiTokenCache)
	openAITokenProvider := service.ProvideOpenAITokenProvider(accountRepository, geminiTokenCache, openAIOAuthService, oAuthRefreshAPI)
	channelRepository := repository.NewChannelRepository(db)
	apiKeyAuthCacheInvalidator := service.ProvideAPIKeyAuthCacheInvalidator(apiKeyService)
	channelService := service.NewChannelService(channelRepository, groupRepository, apiKeyAuthCacheInvalidator, pricingService)
	modelPricingResolver := service.NewModelPricingResolver(channelService, billingService)
	emailCache := repository.NewEmailCache(redisClient)
	emailService := service.NewEmailService(settingRepository, emailCache)
	notificationEmailService := service.NewNotificationEmailService(settingRepository, emailService)
	balanceNotifyService := service.ProvideBalanceNotifyService(emailService, settingRepository, accountRepository, notificationEmailService)
	openAIGatewayService := service.NewOpenAIGatewayService(accountRepository, usageLogRepository, usageBillingRepository, userRepository, userSubscriptionRepository, userGroupRateRepository, gatewayCache, configConfig, schedulerSnapshotService, concurrencyService, billingService, rateLimitService, billingCacheService, httpUpstream, deferredService, openAITokenProvider, modelPricingResolver, channelService, balanceNotifyService, settingService)
	orchestratorAccountSelector := provideAccountSelector(openAIGatewayService)
	mainCleanupAnchor, cleanup, err := provideCleanup(client, redisClient, timingWheelService, schedulerSnapshotService, deferredService, pricingService, billingCacheService, openAIGatewayService, openAIOAuthService)
	if err != nil {
		return nil, nil, err
	}
	usageRecorder := provideUsageRecorderWithCleanup(mainCleanupAnchor)
	orchestratorService := orchestrator.NewService(keyAuthenticator, orchestratorAccountSelector, usageRecorder)
	return orchestratorService, func() {
		cleanup()
	}, nil
}

// wire.go:

type cleanupAnchor struct{}

func provideUsageRecorderWithCleanup(_ *cleanupAnchor) orchestrator.UsageRecorder {
	return provideUsageRecorder()
}

func provideCleanup(
	entClient *ent.Client,
	rdb *redis.Client,
	timingWheel *service.TimingWheelService,
	schedulerSnapshot *service.SchedulerSnapshotService,
	deferred *service.DeferredService,
	pricing *service.PricingService,
	billingCache *service.BillingCacheService,
	openAIGateway *service.OpenAIGatewayService,
	openAIOAuth *service.OpenAIOAuthService,
) (*cleanupAnchor, func(), error) {
	cleanup := func() {
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()

		steps := []struct {
			name string
			fn   func() error
		}{
			{"OpenAIWSPool", func() error {
				if openAIGateway != nil {
					openAIGateway.CloseOpenAIWSPool()
				}
				return nil
			}},
			{"SchedulerSnapshotService", func() error {
				if schedulerSnapshot != nil {
					schedulerSnapshot.Stop()
				}
				return nil
			}},
			{"DeferredService", func() error {
				if deferred != nil {
					deferred.Stop()
				}
				return nil
			}},
			{"PricingService", func() error {
				if pricing != nil {
					pricing.Stop()
				}
				return nil
			}},
			{"BillingCacheService", func() error {
				if billingCache != nil {
					billingCache.Stop()
				}
				return nil
			}},
			{"OpenAIOAuthService", func() error {
				if openAIOAuth != nil {
					openAIOAuth.Stop()
				}
				return nil
			}},
			{"TimingWheelService", func() error {
				if timingWheel != nil {
					timingWheel.Stop()
				}
				return nil
			}},
			{"Redis", func() error {
				if rdb == nil {
					return nil
				}
				return rdb.Close()
			}},
			{"Ent", func() error {
				if entClient == nil {
					return nil
				}
				return entClient.Close()
			}},
		}

		for _, step := range steps {
			if err := step.fn(); err != nil {
				log.Printf("[Cleanup] %s failed: %v", step.name, err)
				continue
			}
			log.Printf("[Cleanup] %s succeeded", step.name)
		}

		select {
		case <-ctx.Done():
			log.Printf("[Cleanup] Warning: cleanup timed out after 10 seconds")
		default:
			log.Printf("[Cleanup] All cleanup steps completed")
		}
	}
	return &cleanupAnchor{}, cleanup, nil
}
